[aws]
aws_access_key_id = "AKIA4HWJT353HUXY7HSG"  # Replace with your AWS access key
aws_secret_access_key = "jJuZNDeQ81Kejf/nz5B427kqxnbJl53/llUQ5yoc"  # Replace with your AWS secret key
region = "us-east-1"  # Replace with your AWS region
